# Generated by Django 5.2.16 on 2026-07-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt", models.PositiveIntegerField(blank=True, null=True)),
                ("phase", models.CharField(default="PreparingWorkspace", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("workspace_path", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("pull_request_url", models.URLField(blank=True, max_length=1000)),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_tokens", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("turn_id", models.CharField(blank=True, max_length=255)),
                ("process_id", models.CharField(blank=True, max_length=64)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("last_event", models.CharField(blank=True, max_length=255)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_message", models.JSONField(blank=True, default=dict)),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_tokens", models.PositiveBigIntegerField(default=0)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="tempo_web.agentrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackedIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tracker_kind", models.CharField(max_length=32)),
                ("external_id", models.CharField(max_length=255)),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("native_ref", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_synced_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tracker_kind", "external_id"), name="tempo_unique_tracker_issue"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="tempo_web.trackedissue",
            ),
        ),
        migrations.CreateModel(
            name="ValidationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("invalidated", "Invalidated"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("workspace_fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="tempo_web.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("command", models.TextField()),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                ("cleanup", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="tempo_web.validationattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["status", "-started_at"], name="tempo_web_a_status_e6d00b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["issue", "-started_at"], name="tempo_web_a_issue_i_b4ef52_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="validationcommand",
            constraint=models.UniqueConstraint(
                fields=("validation", "position"), name="tempo_unique_validation_command_position"
            ),
        ),
    ]
