# Generated by Django 5.2.16 on 2026-07-28 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.CharField(max_length=255, unique=True)),
                ("kind", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("details", models.JSONField(default=dict)),
                ("proposed_arguments", models.JSONField(blank=True, default=dict)),
                ("edited_arguments", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["requested_at"],
            },
        ),
        migrations.CreateModel(
            name="CredentialReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=100)),
                ("secret_reference", models.CharField(max_length=1000)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["project", "name"],
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                ("workspace_root", models.TextField(blank=True)),
                ("max_concurrent_runs", models.PositiveIntegerField(default=3)),
                ("policy", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["project", "slug"],
            },
        ),
        migrations.CreateModel(
            name="OperatorAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("max_concurrent_runs", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["organization__slug", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("external_ref", models.CharField(max_length=500)),
                ("clone_url", models.URLField(blank=True, max_length=1000)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["project", "provider", "external_ref"],
            },
        ),
        migrations.CreateModel(
            name="RunCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["run", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="WorkerLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("worker_id", models.CharField(db_index=True, max_length=255)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("acquired_at", models.DateTimeField()),
                ("heartbeat_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-acquired_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="issue-to-pull-request", max_length=255)),
                ("version", models.PositiveIntegerField()),
                ("path", models.TextField()),
                ("checksum", models.CharField(max_length=64)),
                ("config", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["project", "name", "-version"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="trackedissue",
            name="tempo_unique_tracker_issue",
        ),
        migrations.AddField(
            model_name="agentrun",
            name="available_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="checkpoint",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="lease_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="priority",
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="worker_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("waiting_approval", "Waiting for approval"),
                    ("retry_scheduled", "Retry scheduled"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="running",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tempo_approval_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="tempo_web.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="tempo_web.environment",
            ),
        ),
        migrations.AddField(
            model_name="operatoraction",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tempo_operator_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operatoraction",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operator_actions",
                to="tempo_web.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="tempo_web.organization",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="tempo_web.project",
            ),
        ),
        migrations.AddField(
            model_name="credentialreference",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="tempo_web.project",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="tempo_web.project",
            ),
        ),
        migrations.AddField(
            model_name="trackedissue",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="tempo_web.project",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="tempo_web.project",
            ),
        ),
        migrations.AddField(
            model_name="trackedissue",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="tempo_web.repository",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackedissue",
            constraint=models.UniqueConstraint(
                fields=("project", "tracker_kind", "external_id"),
                name="tempo_unique_project_tracker_issue",
            ),
        ),
        migrations.AddField(
            model_name="runcheckpoint",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoints",
                to="tempo_web.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="workerlease",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leases",
                to="tempo_web.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="workflowversion",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="tempo_web.project",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="workflow_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="tempo_web.workflowversion",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["status", "available_at", "priority"], name="tempo_web_a_status_b6e977_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="tempo_unique_organization_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.UniqueConstraint(
                fields=("project", "slug"), name="tempo_unique_project_environment"
            ),
        ),
        migrations.AddConstraint(
            model_name="credentialreference",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="tempo_unique_project_credential"
            ),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("project", "provider", "external_ref"),
                name="tempo_unique_project_repository",
            ),
        ),
        migrations.AddConstraint(
            model_name="runcheckpoint",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="tempo_unique_run_checkpoint_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowversion",
            constraint=models.UniqueConstraint(
                fields=("project", "name", "version"), name="tempo_unique_project_workflow_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowversion",
            constraint=models.UniqueConstraint(
                fields=("project", "checksum"), name="tempo_unique_project_workflow_checksum"
            ),
        ),
    ]
