# Generated by Django 5.2.16 on 2026-08-02 19:41
# ruff: noqa: E501

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_web', '0003_scope_legacy_runtime_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRuntimeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runtimes', to='tempo_web.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelProviderDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_providers', to='tempo_web.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToolProviderDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_providers', to='tempo_web.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('prompt', models.TextField(blank=True)),
                ('max_turns', models.PositiveIntegerField(blank=True, null=True)),
                ('completion', models.CharField(default='publication', max_length=32)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to='tempo_web.project')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_profiles', to='tempo_web.agentruntimedefinition')),
                ('model_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_profiles', to='tempo_web.modelproviderdefinition')),
                ('tool_providers', models.ManyToManyField(related_name='agent_profiles', to='tempo_web.toolproviderdefinition')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(max_length=32)),
                ('prompt', models.TextField(blank=True)),
                ('max_retries', models.PositiveIntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_nodes', to='tempo_web.agentprofile')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tempo_web.workflowversion')),
            ],
            options={
                'ordering': ['workflow_version', 'position', 'key'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='succeeded', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='tempo_web.workflowversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='tempo_web.workflownodedefinition')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='tempo_web.workflownodedefinition')),
            ],
            options={
                'ordering': ['workflow_version', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RunNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(max_length=32)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('runtime', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='tempo_web.agentrun')),
                ('node_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='tempo_web.workflownodedefinition')),
            ],
            options={
                'ordering': ['run', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentruntimedefinition',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='tempo_unique_project_agent_runtime'),
        ),
        migrations.AddConstraint(
            model_name='modelproviderdefinition',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='tempo_unique_project_model_provider'),
        ),
        migrations.AddConstraint(
            model_name='toolproviderdefinition',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='tempo_unique_project_tool_provider'),
        ),
        migrations.AddConstraint(
            model_name='agentprofile',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='tempo_unique_project_agent_profile'),
        ),
        migrations.AddConstraint(
            model_name='workflownodedefinition',
            constraint=models.UniqueConstraint(fields=('workflow_version', 'key'), name='tempo_unique_workflow_node'),
        ),
        migrations.AddConstraint(
            model_name='workflowedgedefinition',
            constraint=models.UniqueConstraint(fields=('workflow_version', 'source', 'target'), name='tempo_unique_workflow_edge'),
        ),
        migrations.AddConstraint(
            model_name='runnode',
            constraint=models.UniqueConstraint(fields=('run', 'node_key'), name='tempo_unique_run_node'),
        ),
    ]
