# Generated by Django 5.2.16 on 2026-08-02 19:44
# ruff: noqa: E501

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_web', '0004_agentruntimedefinition_modelproviderdefinition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfigurationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_configuration_changes', to='tempo_web.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tempo_platform_configuration_changes', to=settings.AUTH_USER_MODEL)),
                ('workflow_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_changes', to='tempo_web.workflowversion')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
