# Generated by Django 5.2.16 on 2026-08-02 20:05
# ruff: noqa: E501

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_web', '0005_platformconfigurationchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedPlatformConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_platform_configuration', to='tempo_web.project')),
            ],
            options={
                'ordering': ['project'],
            },
        ),
    ]
