# Generated by Django 5.2.16 on 2026-08-02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0006_managedplatformconfiguration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ManagedPlatformConfiguration",
            new_name="WorkflowConfiguration",
        ),
        migrations.RenameField(
            model_name="workflowconfiguration",
            old_name="sections",
            new_name="configuration",
        ),
        migrations.AlterField(
            model_name="workflowconfiguration",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_configuration",
                to="tempo_web.project",
            ),
        ),
        migrations.AlterField(
            model_name="workflowconfiguration",
            name="configuration",
            field=models.JSONField(
                default=dict,
                help_text=(
                    "JSON object containing runtime_providers, model_providers, tool_providers, "
                    "agents, and workflow. Changes are validated and loaded without a restart."
                ),
            ),
        ),
        migrations.AddField(
            model_name="workflowconfiguration",
            name="name",
            field=models.CharField(default="Default workflow", max_length=255),
        ),
        migrations.AddField(
            model_name="workflowconfiguration",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workflowconfiguration",
            name="revision",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="workflowconfiguration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="workflowconfiguration",
            options={
                "ordering": ["project"],
                "verbose_name": "workflow configuration",
                "verbose_name_plural": "workflow configurations",
            },
        ),
    ]
