# Generated by Django 5.2.16 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_web', '0009_runnode_thread_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationattempt',
            name='policy_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='validationattempt',
            name='required_check_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='validationcommand',
            name='check_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
