# Generated by Django 5.2.16 on 2026-09-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_web', '0011_redact_workflow_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='execution_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='snapshot_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='execution_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
