# Generated by Django 5.2.16 on 2026-09-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_web', '0012_execution_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='fresh_workspace_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='restarted_from',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='successor', to='tempo_web.agentrun',
            ),
        ),
    ]
