# Generated by Django 5.2.16 on 2026-09-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0014_productbrief_briefrevision_executionplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="execution_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="tempo_web.executionplan",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="product_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="product_snapshot_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
