# Generated by Django 5.2.16 on 2026-09-07 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0015_agentrun_execution_plan_agentrun_product_snapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField()),
                ("data", models.BinaryField()),
                ("manifest", models.JSONField()),
                ("manifest_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="build_artifacts",
                        to="tempo_web.agentrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "manifest_digest"), name="tempo_unique_run_build_manifest"
                    )
                ],
            },
        ),
    ]
