# Generated by Django 5.2.16 on 2026-09-08 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0017_preview_deployment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptanceSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("specification", models.JSONField()),
                ("digest", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptance_suites",
                        to="tempo_web.buildartifact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcceptanceAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.UUIDField(unique=True)),
                ("status", models.CharField(db_index=True, default="queued", max_length=20)),
                ("image", models.CharField(max_length=80)),
                ("identity", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("report", models.JSONField(default=dict)),
                ("report_digest", models.CharField(blank=True, max_length=64)),
                ("error", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="tempo_web.acceptancesuite",
                    ),
                ),
            ],
        ),
    ]
