# Generated by Django 5.2.16 on 2026-09-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0018_acceptance_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviewHealthAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.UUIDField(unique=True)),
                ("status", models.CharField(db_index=True, default="queued", max_length=20)),
                ("identity", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("report", models.JSONField(default=dict)),
                ("report_digest", models.CharField(blank=True, max_length=64)),
                ("error", models.TextField(blank=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_attempts",
                        to="tempo_web.previewdeployment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
