# Generated by Django 5.2.16 on 2026-09-08 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0019_preview_health_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=48)),
                ("slot", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_targets",
                        to="tempo_web.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("specification", models.JSONField()),
                ("digest", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_configurations",
                        to="tempo_web.buildartifact",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="tempo_web.deploymenttarget",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="deploymenttarget",
            constraint=models.UniqueConstraint(
                fields=("project", "key"), name="tempo_unique_deployment_target"
            ),
        ),
    ]
