# Generated by Django 5.2.16 on 2026-09-08 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0020_release_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RollbackRehearsal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.UUIDField(unique=True)),
                ("slot", models.UUIDField(unique=True)),
                ("bundle", models.UUIDField(unique=True)),
                ("identity", models.JSONField()),
                ("status", models.CharField(db_index=True, default="queued", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("report", models.JSONField(default=dict)),
                ("report_digest", models.CharField(blank=True, max_length=64)),
                ("error", models.TextField(blank=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehearsals",
                        to="tempo_web.releaseconfiguration",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehearsals",
                        to="tempo_web.deploymenttarget",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["queued", "running", "cleanup_pending"])
                        ),
                        fields=("target",),
                        name="tempo_one_active_rollback_rehearsal",
                    )
                ],
            },
        ),
    ]
