# Generated by Django 5.2.16 on 2026-09-08 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0021_rollback_rehearsal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.UUIDField(unique=True)),
                ("bundle", models.UUIDField(unique=True)),
                ("probe_slot", models.UUIDField(unique=True)),
                ("identity", models.JSONField()),
                ("identity_digest", models.CharField(max_length=64)),
                ("status", models.CharField(db_index=True, default="queued", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("authorization", models.JSONField(default=dict)),
                ("authorization_digest", models.CharField(blank=True, max_length=64)),
                ("report", models.JSONField(default=dict)),
                ("report_digest", models.CharField(blank=True, max_length=64)),
                ("recovery_report", models.JSONField(default=dict)),
                ("recovery_digest", models.CharField(blank=True, max_length=64)),
                ("recovery_attempts", models.PositiveIntegerField(default=0)),
                ("rollback_requested_at", models.DateTimeField(null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="tempo_web.releaseconfiguration",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rollback_requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_release_rollbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="tempo_web.deploymenttarget",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "queued",
                                    "running",
                                    "rollback_queued",
                                    "recovering",
                                    "recovery_pending",
                                    "needs_attention",
                                ],
                            )
                        ),
                        fields=("target",),
                        name="tempo_one_active_release_operation",
                    )
                ],
            },
        ),
    ]
