# Generated by Django 5.2.16 on 2026-09-12 10:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0022_release_publication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("provider", models.CharField(default="codex", editable=False, max_length=32)),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[
                            ("codex-file", "Provisioned Codex ChatGPT login"),
                            ("installation", "Existing installation login"),
                        ],
                        max_length=32,
                    ),
                ),
                ("disabled", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("credential_generation", models.PositiveIntegerField(default=0)),
                ("identity_fingerprint", models.CharField(blank=True, max_length=64)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_status", models.CharField(default="pending", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tempo_web.organization"
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "label", "id"],
            },
        ),
        migrations.CreateModel(
            name="AgentAccountEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("revision", models.PositiveIntegerField()),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="tempo_web.agentaccount",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AgentAccountGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="tempo_web.agentaccount",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tempo_web.project"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="agentaccount",
            constraint=models.UniqueConstraint(
                fields=("organization", "label"), name="tempo_unique_account_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentaccountgrant",
            constraint=models.UniqueConstraint(
                fields=("account", "project"), name="tempo_unique_account_project_grant"
            ),
        ),
    ]
