# Generated by Django 5.2.16 on 2026-09-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tempo_web", "0023_agent_account_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAccountAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=100)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("binding", models.JSONField()),
                ("status", models.CharField(default="starting", max_length=32)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="tempo_web.agentaccount",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_attempts",
                        to="tempo_web.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
